admin:
  ip: 0.0.0.0
  port: 9990


#routers:
#  - protocol: http
#    dtab: /svc => /$/inet/127.1/8888
#    servers:
#      - ip: 0.0.0.0
#        port: 4140

# /helloworld.Greeter/SayHello


routers:
  - protocol: h2
    label: grpc
    servers:
      - port: 4142
    identifier:
      kind: io.l5d.header.path
      segments: 2
    dtab:
      /svc => /$/inet/127.1/50051